version: '3'
services:
  node:
    build: tp-docker-compose
    ports:
      - 2300:80
    environment:
      - mongo_connection=mongodb://mongo:27017
    networks:
      - network
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - network
    volumes: 
      - db:/data/db

networks:
  network:
    driver: bridge
volumes:
  db:
