version: '3'
services:
  node:
    build: .
    image: nodejs
    ports:
      - 6800:3000
    environment:
      - mongo_connection=mongodb://mongo:27017
      - POSTGRES_CONNECTION=postgres://user:pass@postgres:5432/db
    networks:
      - network
  mongo:
    image: mongo
    networks:
      - network
    volumes:
      - db:/data/db
  postgres:
    image:  postgres
    networks:
        - network
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: db
    volumes:
        - db:/var/lib/postgresql/data
networks:
  network:
    driver: bridge
volumes:
  db:
